# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\huyquang\project\company\test\resources\ui\login_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 400)
        Dialog.setStyleSheet("background-color: #f5f5f5;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(40, 30, 40, 30)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.comboBox_language = QtWidgets.QComboBox(Dialog)
        self.comboBox_language.setMinimumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_language.setFont(font)
        self.comboBox_language.setStyleSheet("QComboBox {\n"
                                             "    border: 1px solid #c0c0c0;\n"
                                             "    border-radius: 4px;\n"
                                             "    padding: 1px 6px;\n"
                                             "    background-color: white;\n"
                                             "}\n"
                                             "QComboBox:hover {\n"
                                             "    border: 1px solid #4a90e2;\n"
                                             "}\n"
                                             "QComboBox::drop-down {\n"
                                             "    subcontrol-origin: padding;\n"
                                             "    subcontrol-position: top right;\n"
                                             "    width: 20px;\n"
                                             "    border-left-width: 1px;\n"
                                             "    border-left-color: #c0c0c0;\n"
                                             "    border-left-style: solid;\n"
                                             "}")
        self.comboBox_language.setObjectName("comboBox_language")
        self.comboBox_language.addItem("")
        self.comboBox_language.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_language)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.qlabel_logo = QtWidgets.QLabel(Dialog)
        self.qlabel_logo.setMinimumSize(QtCore.QSize(80, 80))
        self.qlabel_logo.setText("")
        self.qlabel_logo.setPixmap(QtGui.QPixmap(
            "c:\\huyquang\\project\\company\\test\\resources\\ui\\../images/logo.png"))
        self.qlabel_logo.setScaledContents(False)
        self.qlabel_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.qlabel_logo.setObjectName("qlabel_logo")
        self.verticalLayout.addWidget(self.qlabel_logo)
        self.qlabel_title = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.qlabel_title.setFont(font)
        self.qlabel_title.setStyleSheet("color: #2d2d30;")
        self.qlabel_title.setAlignment(QtCore.Qt.AlignCenter)
        self.qlabel_title.setObjectName("qlabel_title")
        self.verticalLayout.addWidget(self.qlabel_title)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.qlabel_username = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.qlabel_username.setFont(font)
        self.qlabel_username.setObjectName("qlabel_username")
        self.verticalLayout.addWidget(self.qlabel_username)
        self.qline_username = QtWidgets.QLineEdit(Dialog)
        self.qline_username.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.qline_username.setFont(font)
        self.qline_username.setStyleSheet("QLineEdit {\n"
                                          "    border: 1px solid #c0c0c0;\n"
                                          "    border-radius: 4px;\n"
                                          "    padding: 2px 8px;\n"
                                          "    background-color: white;\n"
                                          "}\n"
                                          "QLineEdit:focus {\n"
                                          "    border: 1px solid #4a90e2;\n"
                                          "}")
        self.qline_username.setObjectName("qline_username")
        self.verticalLayout.addWidget(self.qline_username)
        self.qlabel_password = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.qlabel_password.setFont(font)
        self.qlabel_password.setObjectName("qlabel_password")
        self.verticalLayout.addWidget(self.qlabel_password)
        self.qline_password = QtWidgets.QLineEdit(Dialog)
        self.qline_password.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.qline_password.setFont(font)
        self.qline_password.setStyleSheet("QLineEdit {\n"
                                          "    border: 1px solid #c0c0c0;\n"
                                          "    border-radius: 4px;\n"
                                          "    padding: 2px 8px;\n"
                                          "    background-color: white;\n"
                                          "}\n"
                                          "QLineEdit:focus {\n"
                                          "    border: 1px solid #4a90e2;\n"
                                          "}")
        self.qline_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.qline_password.setObjectName("qline_password")
        self.verticalLayout.addWidget(self.qline_password)
        self.qcheckbox_remember_me = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.qcheckbox_remember_me.setFont(font)
        self.qcheckbox_remember_me.setStyleSheet("color: #555555;")
        self.qcheckbox_remember_me.setObjectName("qcheckbox_remember_me")
        self.verticalLayout.addWidget(self.qcheckbox_remember_me)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.btn_login = QtWidgets.QPushButton(Dialog)
        self.btn_login.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("QPushButton {\n"
                                     "    background-color: #4a90e2;\n"
                                     "    color: white;\n"
                                     "    border-radius: 4px;\n"
                                     "    padding: 6px;\n"
                                     "}\n"
                                     "QPushButton:hover {\n"
                                     "    background-color: #3a80d2;\n"
                                     "}\n"
                                     "QPushButton:pressed {\n"
                                     "    background-color: #2a70c2;\n"
                                     "}")
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout.addWidget(self.btn_login)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Login"))
        self.comboBox_language.setItemText(0, _translate("Dialog", "English"))
        self.comboBox_language.setItemText(
            1, _translate("Dialog", "Vietnamese"))
        self.qlabel_title.setText(_translate("Dialog", "Welcome Back"))
        self.qlabel_username.setText(_translate("Dialog", "Username"))
        self.qline_username.setPlaceholderText(
            _translate("Dialog", "Enter your username"))
        self.qlabel_password.setText(_translate("Dialog", "Password"))
        self.qline_password.setPlaceholderText(
            _translate("Dialog", "Enter your password"))
        self.qcheckbox_remember_me.setText(_translate("Dialog", "Remember me"))
        self.btn_login.setText(_translate("Dialog", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
