# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\huyquang\project\company\ptz-chp\resources\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 838)
        MainWindow.setStyleSheet("QMainWindow {\n"
                                 "    background-color: #f5f5f5;\n"
                                 "    color: #333333;\n"
                                 "}\n"
                                 "QLabel {\n"
                                 "    color: #333333;\n"
                                 "    font-family: \"Segoe UI\";\n"
                                 "    font-size: 12px;\n"
                                 "}\n"
                                 "QPushButton {\n"
                                 "    background-color: #4a90e2;\n"
                                 "    color: white;\n"
                                 "    border-radius: 4px;\n"
                                 "    padding: 8px 16px;\n"
                                 "    font-family: \"Segoe UI\";\n"
                                 "    font-size: 12px;\n"
                                 "    font-weight: bold;\n"
                                 "    min-height: 30px;\n"
                                 "    transition: all 0.3s;\n"
                                 "}\n"
                                 "QPushButton:hover {\n"
                                 "    background-color: #3a80d2;\n"
                                 "    transform: translateY(-2px);\n"
                                 "    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\n"
                                 "}\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: #2a70c2;\n"
                                 "    transform: translateY(1px);\n"
                                 "    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n"
                                 "    animation-name: button-press;\n"
                                 "    animation-duration: 0.2s;\n"
                                 "}\n"
                                 "@keyframes button-press {\n"
                                 "    0% { transform: scale(1); }\n"
                                 "    50% { transform: scale(0.97); }\n"
                                 "    100% { transform: scale(1); }\n"
                                 "}\n"
                                 "QComboBox {\n"
                                 "    border: 1px solid #c0c0c0;\n"
                                 "    border-radius: 4px;\n"
                                 "    padding: 4px 8px;\n"
                                 "    background-color: white;\n"
                                 "    color: #333333;\n"
                                 "    font-family: \"Segoe UI\";\n"
                                 "    min-height: 30px;\n"
                                 "    transition: border 0.3s;\n"
                                 "}\n"
                                 "QComboBox:hover {\n"
                                 "    border: 1px solid #4a90e2;\n"
                                 "}\n"
                                 "QComboBox:pressed {\n"
                                 "    animation-name: combo-press;\n"
                                 "    animation-duration: 0.2s;\n"
                                 "}\n"
                                 "@keyframes combo-press {\n"
                                 "    0% { transform: scale(1); }\n"
                                 "    50% { transform: scale(0.97); }\n"
                                 "    100% { transform: scale(1); }\n"
                                 "}\n"
                                 "QComboBox::drop-down {\n"
                                 "    subcontrol-origin: padding;\n"
                                 "    subcontrol-position: top right;\n"
                                 "    width: 20px;\n"
                                 "    border-left-width: 1px;\n"
                                 "    border-left-color: #c0c0c0;\n"
                                 "    border-left-style: solid;\n"
                                 "}\n"
                                 "QSlider::groove:horizontal {\n"
                                 "    border: 1px solid #c0c0c0;\n"
                                 "    height: 8px;\n"
                                 "    background: white;\n"
                                 "    margin: 2px 0;\n"
                                 "    border-radius: 4px;\n"
                                 "}\n"
                                 "QSlider::handle:horizontal {\n"
                                 "    background: #4a90e2;\n"
                                 "    border: 1px solid #4a90e2;\n"
                                 "    width: 18px;\n"
                                 "    height: 18px;\n"
                                 "    margin: -6px 0;\n"
                                 "    border-radius: 9px;\n"
                                 "    transition: background 0.2s;\n"
                                 "}\n"
                                 "QSlider::handle:horizontal:hover {\n"
                                 "    background: #3a80d2;\n"
                                 "}\n"
                                 "QSlider::handle:horizontal:pressed {\n"
                                 "    background: #2a70c2;\n"
                                 "    animation-name: slider-press;\n"
                                 "    animation-duration: 0.2s;\n"
                                 "}\n"
                                 "@keyframes slider-press {\n"
                                 "    0% { transform: scale(1); }\n"
                                 "    50% { transform: scale(0.9); }\n"
                                 "    100% { transform: scale(1); }\n"
                                 "}\n"
                                 "QFrame {\n"
                                 "    border-radius: 8px;\n"
                                 "    background-color: white;\n"
                                 "    border: 1px solid #e0e0e0;\n"
                                 "}\n"
                                 "QLineEdit {\n"
                                 "    border: 1px solid #c0c0c0;\n"
                                 "    border-radius: 4px;\n"
                                 "    padding: 4px 8px;\n"
                                 "    background-color: white;\n"
                                 "    color: #333333;\n"
                                 "    font-family: \"Segoe UI\";\n"
                                 "    min-height: 30px;\n"
                                 "    transition: border 0.3s;\n"
                                 "}\n"
                                 "QLineEdit:hover {\n"
                                 "    border: 1px solid #4a90e2;\n"
                                 "}\n"
                                 "QLineEdit:focus {\n"
                                 "    border: 1px solid #4a90e2;\n"
                                 "    animation-name: focus-animation;\n"
                                 "    animation-duration: 0.3s;\n"
                                 "}\n"
                                 "@keyframes focus-animation {\n"
                                 "    0% { border-color: #c0c0c0; }\n"
                                 "    100% { border-color: #4a90e2; }\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.qlabel_camera_view = QtWidgets.QLabel(self.centralwidget)
        self.qlabel_camera_view.setMinimumSize(QtCore.QSize(700, 400))
        self.qlabel_camera_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.qlabel_camera_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.qlabel_camera_view.setAlignment(QtCore.Qt.AlignCenter)
        self.qlabel_camera_view.setObjectName("qlabel_camera_view")
        self.verticalLayout.addWidget(self.qlabel_camera_view)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_up = QtWidgets.QPushButton(self.centralwidget)
        self.btn_up.setMinimumSize(QtCore.QSize(60, 46))
        self.btn_up.setObjectName("btn_up")
        self.gridLayout.addWidget(self.btn_up, 0, 1, 1, 1)
        self.btn_left = QtWidgets.QPushButton(self.centralwidget)
        self.btn_left.setMinimumSize(QtCore.QSize(60, 46))
        self.btn_left.setObjectName("btn_left")
        self.gridLayout.addWidget(self.btn_left, 1, 0, 1, 1)
        self.btn_center = QtWidgets.QPushButton(self.centralwidget)
        self.btn_center.setMinimumSize(QtCore.QSize(60, 46))
        self.btn_center.setStyleSheet("background-color: #e0e0e0;\n"
                                      "color: #333333;\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: #c0c0c0;\n"
                                      "    animation-name: center-press;\n"
                                      "    animation-duration: 0.2s;\n"
                                      "}\n"
                                      "@keyframes center-press {\n"
                                      "    0% { transform: scale(1); }\n"
                                      "    50% { transform: scale(0.95); }\n"
                                      "    100% { transform: scale(1); }\n"
                                      "}")
        self.btn_center.setObjectName("btn_center")
        self.gridLayout.addWidget(self.btn_center, 1, 1, 1, 1)
        self.btn_right = QtWidgets.QPushButton(self.centralwidget)
        self.btn_right.setMinimumSize(QtCore.QSize(60, 46))
        self.btn_right.setObjectName("btn_right")
        self.gridLayout.addWidget(self.btn_right, 1, 2, 1, 1)
        self.btn_down = QtWidgets.QPushButton(self.centralwidget)
        self.btn_down.setMinimumSize(QtCore.QSize(60, 46))
        self.btn_down.setObjectName("btn_down")
        self.gridLayout.addWidget(self.btn_down, 2, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_zoom_in = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zoom_in.setMinimumSize(QtCore.QSize(100, 46))
        self.btn_zoom_in.setObjectName("btn_zoom_in")
        self.verticalLayout_2.addWidget(self.btn_zoom_in)
        self.btn_zoom_out = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zoom_out.setMinimumSize(QtCore.QSize(100, 46))
        self.btn_zoom_out.setObjectName("btn_zoom_out")
        self.verticalLayout_2.addWidget(self.btn_zoom_out)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.qslider_ptz_speed = QtWidgets.QSlider(self.centralwidget)
        self.qslider_ptz_speed.setMinimumSize(QtCore.QSize(180, 30))
        self.qslider_ptz_speed.setMinimum(1)
        self.qslider_ptz_speed.setMaximum(10)
        self.qslider_ptz_speed.setProperty("value", 5)
        self.qslider_ptz_speed.setOrientation(QtCore.Qt.Horizontal)
        self.qslider_ptz_speed.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.qslider_ptz_speed.setTickInterval(1)
        self.qslider_ptz_speed.setObjectName("qslider_ptz_speed")
        self.verticalLayout_4.addWidget(self.qslider_ptz_speed)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_capture_auto = QtWidgets.QPushButton(self.centralwidget)
        self.btn_capture_auto.setMinimumSize(QtCore.QSize(0, 46))
        self.btn_capture_auto.setStyleSheet("background-color: #e67e22;\n"
                                            "QPushButton:hover {\n"
                                            "    background-color: #d35400;\n"
                                            "}\n"
                                            "QPushButton:pressed {\n"
                                            "    background-color: #c04a00;\n"
                                            "    animation-name: auto-press;\n"
                                            "    animation-duration: 0.2s;\n"
                                            "}\n"
                                            "@keyframes auto-press {\n"
                                            "    0% { transform: scale(1); }\n"
                                            "    50% { transform: scale(0.97); }\n"
                                            "    100% { transform: scale(1); }\n"
                                            "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            "c:\\huyquang\\project\\company\\ptz-chp\\resources\\ui\\../assets/icons/auto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_capture_auto.setIcon(icon)
        self.btn_capture_auto.setObjectName("btn_capture_auto")
        self.horizontalLayout_3.addWidget(self.btn_capture_auto)
        self.btn_capture = QtWidgets.QPushButton(self.centralwidget)
        self.btn_capture.setMinimumSize(QtCore.QSize(0, 46))
        self.btn_capture.setStyleSheet("background-color: #00a86b;\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: #009c63;\n"
                                       "}\n"
                                       "QPushButton:pressed {\n"
                                       "    background-color: #008c59;\n"
                                       "    animation-name: capture-press;\n"
                                       "    animation-duration: 0.2s;\n"
                                       "}\n"
                                       "@keyframes capture-press {\n"
                                       "    0% { transform: scale(1); }\n"
                                       "    50% { transform: scale(0.97); }\n"
                                       "    100% { transform: scale(1); }\n"
                                       "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            "c:\\huyquang\\project\\company\\ptz-chp\\resources\\ui\\../assets/icons/camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_capture.setIcon(icon1)
        self.btn_capture.setObjectName("btn_capture")
        self.horizontalLayout_3.addWidget(self.btn_capture)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.frame_controls = QtWidgets.QFrame(self.centralwidget)
        self.frame_controls.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_controls.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_controls.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_controls.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_controls.setObjectName("frame_controls")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_controls)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_camera = QtWidgets.QComboBox(self.frame_controls)
        self.comboBox_camera.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_camera.setObjectName("comboBox_camera")
        self.comboBox_camera.addItem("")
        self.comboBox_camera.addItem("")
        self.comboBox_camera.addItem("")
        self.comboBox_camera.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_camera, 1, 0, 1, 1)
        self.btn_reload = QtWidgets.QPushButton(self.frame_controls)
        self.btn_reload.setMinimumSize(QtCore.QSize(0, 46))
        self.btn_reload.setStyleSheet("background-color: #5c6bc0;\n"
                                      "color: white;\n"
                                      "border-radius: 4px;\n"
                                      "font-weight: bold;\n"
                                      "box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: #4a5ab9;\n"
                                      "    transform: translateY(-1px);\n"
                                      "    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: #3949ab;\n"
                                      "    transform: translateY(1px);\n"
                                      "    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);\n"
                                      "    animation-name: reload-press;\n"
                                      "    animation-duration: 0.3s;\n"
                                      "}\n"
                                      "\n"
                                      "@keyframes reload-press {\n"
                                      "    0% { transform: scale(1); }\n"
                                      "    50% { transform: scale(0.95); rotate: -10deg; }\n"
                                      "    100% { transform: scale(1); }\n"
                                      "}")
        self.btn_reload.setObjectName("btn_reload")
        self.gridLayout_2.addWidget(self.btn_reload, 1, 1, 1, 1)
        self.comboBox_language = QtWidgets.QComboBox(self.frame_controls)
        self.comboBox_language.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_language.setObjectName("comboBox_language")
        self.comboBox_language.addItem("")
        self.comboBox_language.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_language, 3, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.frame_controls)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 2)
        self.horizontalLayout.addWidget(self.frame_controls)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "PTZ Camera Controller"))
        self.btn_up.setText(_translate("MainWindow", "▲"))
        self.btn_left.setText(_translate("MainWindow", "◄"))
        self.btn_center.setText(_translate("MainWindow", "●"))
        self.btn_right.setText(_translate("MainWindow", "►"))
        self.btn_down.setText(_translate("MainWindow", "▼"))
        self.btn_zoom_in.setText(_translate("MainWindow", "Zoom +"))
        self.btn_zoom_out.setText(_translate("MainWindow", "Zoom -"))
        self.btn_capture_auto.setText(_translate("MainWindow", "Capture Auto"))
        self.btn_capture.setText(_translate("MainWindow", "Capture"))
        self.comboBox_camera.setItemText(
            0, _translate("MainWindow", "Main Entrance"))
        self.comboBox_camera.setItemText(
            1, _translate("MainWindow", "Parking Lot"))
        self.comboBox_camera.setItemText(2, _translate("MainWindow", "Lobby"))
        self.comboBox_camera.setItemText(
            3, _translate("MainWindow", "Warehouse"))
        self.btn_reload.setText(_translate("MainWindow", "↻"))
        self.comboBox_language.setItemText(
            0, _translate("MainWindow", "English"))
        self.comboBox_language.setItemText(
            1, _translate("MainWindow", "Vietnamese"))
        self.groupBox.setTitle(_translate("MainWindow", "Presets"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
